"""Create initial tables

Revision ID: 2c27e0fbb97c
Revises: 5dc0bf4a24d4
Create Date: 2026-10-04 07:02:17.700457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c27e0fbb97c'
down_revision: Union[str, Sequence[str], None] = '5dc0bf4a24d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
